[tool.black]
target-version = ["py311"]
extend-exclude = "tests/obfuscator/test_names/code/"

[tool.ruff]
fix = true
target-version = "py311"
select = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
include = ["*.py"]
exclude = [
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pypackages__",
    "build",
    "venv",
    "docs",
    "wip/",
    "examples/",
    "hello.py",
]
extend-ignore = ["ERA001", "BLE001", "S311", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "FBT001", "FBT002"]

[tool.ruff.extend-per-file-ignores]
"pof/cli.py" = ["G004"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
known-local-folder = ["pof", "test"]

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
exclude = ["^tests/obfuscator/test_names/code/.*$"]

[tool.pytest.ini_options]
addopts = "-p no:warnings --cov=pof --no-cov-on-fail"
